name: Build and Deploy Code

on: [push, pull_request]

jobs:
  jobs1:
    runs-on: windows-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: setting hello farrukh
        run: echo "posting from far"
